---
title: "Data Wrangling & Final Report Draft"
author: "Rosie Wu"
date: "2025-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
# import libraries
library(here)
library(tidyverse)
library(naniar)
library(DHARMa)
library(gtsummary)
library(broom)
library(ggplot2)
library(dplyr)
```


# Data Wrangling
```{r Import all of the datasets}
# Import all of the datasets first

precipitation_data <- read.csv("./Rosie's Docs/2022 US State Precipitation.csv", 
                 skip = 4,        # Skip first 4 rows
                 header = TRUE)   # Use first row after skipping as header
precipitation_data <- precipitation_data %>% 
  rename(Precip_in = Value)

temp_data <- read.csv("./Rosie's Docs/2022 US State Temperature.csv", 
                 skip = 4,        
                 header = TRUE)
temp_data <- temp_data %>% 
  rename(Temp_F = Value)

population_data <- read.csv("./Rosie's Docs/Population by State 2022.csv", 
                 skip = 3,      
                 header = TRUE)
# This requires formatting to remove the extra dot from the raw data
population_data$State <- gsub("^\\.+", "", population_data$State)

ev_registeration_df <- read.csv("./Rosie's Docs/EV registeration count by state 2022.csv",
                                skip = 1,
                                header = TRUE)

urban_pop_data <- read.csv("./Rosie's Docs/Urban and Rural Data.csv") %>%
  mutate(
    Total = as.numeric(gsub("[,.]+", "", Total)),
    X....Urban = as.numeric(gsub("[,.]+", "", X....Urban))
  )

# add a column for calculating urban / total population ratio for urbanization
# this ratio would be under year 2020, which is the latest data we found
urban_pop_data <- urban_pop_data %>%
  # This converts the ratio to # percent
  mutate(Urbanization = (X....Urban / Total)*100) 

# This is the main data frame to combine all data based on
main_df <- read.csv("./Rosie's Docs/Master Data Frame.csv")
```

```{r Combine into One Dataset for Visuals and Analysis}

df_list <- list(
  main_df[c("State", "PM.2.5", "NO2", "O3..ppm.")],
  population_data[c("State", "X2022")],
  urban_pop_data[c("State", "Urbanization")],
  ev_registeration_df[c("State", "Electric..EV.")],
  temp_data[c("State", "Temp_F")],
  precipitation_data[c("State", "Precip_in")]
  )

combined_df <- Reduce(function(x, y) merge(x, y, by = "State", all = TRUE), df_list)
# remove empty rows
clean_combine_df <- combined_df %>% 
  filter(!is.na(State) & State != "") %>%
  rename(Population_2022 = X2022) %>%
  rename(EV_count = Electric..EV.) %>%
  rename(Ozone_ppm = O3..ppm.)
```


```{r Add EV Registeration Ratio Column to Dataset}
clean_combine_df <- clean_combine_df %>%
  mutate(
    EV_count = as.numeric(gsub(",", "", EV_count)),
    Population_2022 = as.numeric(gsub(",", "", Population_2022)),
    EV_ratio = EV_count / Population_2022
    )
```


